#
# TransFig makefile
#

all: braco-1.tex braco-garra.tex cubo-sem-canto.tex modelagem-jato.tex projecoes-cubo.tex projecoes-indices.tex projecoes-vista-perspectiva.tex tuxfig.tex 

# translation into eps

braco-1.tex: braco-1.eps Makefile
	fig2ps2tex braco-1.eps >braco-1.tex
clean::
	rm -f braco-1.tex

braco-1.eps: braco-1.fig Makefile
	fig2dev -L eps braco-1.fig > braco-1.eps
clean::
	rm -f braco-1.eps


# translation into eps

braco-garra.tex: braco-garra.eps Makefile
	fig2ps2tex braco-garra.eps >braco-garra.tex
clean::
	rm -f braco-garra.tex

braco-garra.eps: braco-garra.fig Makefile
	fig2dev -L eps braco-garra.fig > braco-garra.eps
clean::
	rm -f braco-garra.eps


# translation into eps

cubo-sem-canto.tex: cubo-sem-canto.eps Makefile
	fig2ps2tex cubo-sem-canto.eps >cubo-sem-canto.tex
clean::
	rm -f cubo-sem-canto.tex

cubo-sem-canto.eps: cubo-sem-canto.fig Makefile
	fig2dev -L eps cubo-sem-canto.fig > cubo-sem-canto.eps
clean::
	rm -f cubo-sem-canto.eps


# translation into eps

modelagem-jato.tex: modelagem-jato.eps Makefile
	fig2ps2tex modelagem-jato.eps >modelagem-jato.tex
clean::
	rm -f modelagem-jato.tex

modelagem-jato.eps: modelagem-jato.fig Makefile
	fig2dev -L eps modelagem-jato.fig > modelagem-jato.eps
clean::
	rm -f modelagem-jato.eps


# translation into eps

projecoes-cubo.tex: projecoes-cubo.eps Makefile
	fig2ps2tex projecoes-cubo.eps >projecoes-cubo.tex
clean::
	rm -f projecoes-cubo.tex

projecoes-cubo.eps: projecoes-cubo.fig Makefile
	fig2dev -L eps projecoes-cubo.fig > projecoes-cubo.eps
clean::
	rm -f projecoes-cubo.eps


# translation into eps

projecoes-indices.tex: projecoes-indices.eps Makefile
	fig2ps2tex projecoes-indices.eps >projecoes-indices.tex
clean::
	rm -f projecoes-indices.tex

projecoes-indices.eps: projecoes-indices.fig Makefile
	fig2dev -L eps projecoes-indices.fig > projecoes-indices.eps
clean::
	rm -f projecoes-indices.eps


# translation into eps

projecoes-vista-perspectiva.tex: projecoes-vista-perspectiva.eps Makefile
	fig2ps2tex projecoes-vista-perspectiva.eps >projecoes-vista-perspectiva.tex
clean::
	rm -f projecoes-vista-perspectiva.tex

projecoes-vista-perspectiva.eps: projecoes-vista-perspectiva.fig Makefile
	fig2dev -L eps projecoes-vista-perspectiva.fig > projecoes-vista-perspectiva.eps
clean::
	rm -f projecoes-vista-perspectiva.eps


# translation into eps

tuxfig.tex: tuxfig.eps Makefile
	fig2ps2tex tuxfig.eps >tuxfig.tex
clean::
	rm -f tuxfig.tex

tuxfig.eps: tuxfig.fig Makefile
	fig2dev -L eps tuxfig.fig > tuxfig.eps
clean::
	rm -f tuxfig.eps

